baseurl = "/"
title = "Jake Lowell - Blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Jake Lowell"
disqusShortname = "XXX"
googleAnalytics = "UA-163416155-1"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Blog"
    description = "Site for data analysis"
    github = "https://github.com/jacoblowell"
    #gitlab = "https://gitlab.com/XXX"
    linkedin = "https://www.linkedin.com/in/jacob-lowell-47809712b/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/lowell_jacob"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "jakelowell@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

#[[menu.main]]
 #   name = "Projects"
  #  url = "/project/"
   # weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
