---
title: Oversampling, Undersampling and SMOTE
author: Jacob Lowell
date: '2018-12-26'
slug: oversampling-undersampling-and-smote
categories: []
tags: ["Course Imbalance"]
description: ''
---





```{r , include=FALSE}
 library(tidyverse)
 library(scales)
 lgd <- read_csv("lgd.csv")

hmeq <- read_csv("hmeq.csv")
#creditcard <- read_csv("creditcard.csv")
#remove(creditcard)
prop.table(table(lgd$event,lgd$purpose1))

table(lgd$event)

table(lgd$event,lgd$purpose1)

prop.table(table(lgd$event))


table(hmeq$BAD)

```



```{r,fig.width = 5,fig.asp = 0.618, fig.align='center'}
hmeq %>%  filter(!is.na(VALUE)) %>%
  ggplot( aes(x = VALUE, y = LOAN , color= factor(BAD))) +
  geom_point() +
  scale_color_manual(values = c('dodgerblue', 'red')) + facet_grid(~BAD) + labs(title = "Home Equity Loan Performance by loan amount and value of home")  +scale_y_continuous(labels = scales::dollar) + scale_x_continuous(labels = scales::dollar)
```

**oversampling, unsersampling**

These programs do not work well with missing values.  They only are able to resample for complete cases.

*** level the dataset ***
```{r}
library(ROSE)

#hmeq <- na.omit(hmeq)
table(hmeq$BAD)

#hmeq <- hmeq %>% mutate(fill_notnull = 1)

hmeq$ID <- seq.int(nrow(hmeq))

# for over and under, missing values skew

# Calculate the required number of cases in the over-sampled dataset
 n_new <- 4771/(1-0.5)  # 4771 is the number of goods (non-bad)

# Over-sample
oversampling_result <- ovun.sample(formula = BAD ~ ., data = hmeq,
                           method = "over", N = n_new, seed = 2019)

# Verify the Class-balance of the over-sampled dataset
oversampled_hmeq <- oversampling_result$data
prop.table(table(oversampled_hmeq$BAD))



oversampled_hmeq %>%  ggplot(aes(x = ID , fill = as.factor(BAD) )) + geom_histogram(binwidth =  1) + facet_grid(~BAD)


hmeq_bad_nona <- hmeq %>%  filter(BAD ==1 ) %>%  drop_na()

unique_over_bad <- oversampled_hmeq %>% filter(BAD == 1)

unique_over_bad <- unique_over_bad %>%  group_by(ID) %>%  slice(1) %>% ungroup()

hmeq_good_nona <- hmeq %>%  filter(BAD ==0 ) %>%  drop_na()

unique_over_good <- oversampled_hmeq %>% filter(BAD == 0)

unique_over_good <- unique_over_good %>%  group_by(ID) %>%  slice(1) %>% ungroup()

```




***undersample***

```{r}
table(hmeq$BAD)

 n_new <- 1189/(0.5)  # 4771 is the number of bads (non-goods)

# Over-sample
undersampling_result <- ovun.sample(formula = BAD ~ ., data = hmeq,
                           method = "under", N = n_new, seed = 2019)

# Verify the Class-balance of the over-sampled dataset
undersampled_hmeq <- undersampling_result$data
prop.table(table(undersampled_hmeq$BAD))

```


# combine over and under sample

```{r}
table(hmeq$BAD)

# Specify the desired number of cases in the balanced dataset and the fraction of fraud cases
n_new <- 10000
bad_fraction <- 0.5

# Combine ROS & RUS!
sampling_result <- ovun.sample(formula = BAD ~ ., data = hmeq,
                               method = "both", N = n_new, p = bad_fraction, seed = 2018)

# Verify the Class-balance of the re-balanced dataset
sampled_hmeq <- sampling_result$data
prop.table(table(sampled_hmeq$BAD))


```


## test dups with both way over and under sample

```{r}

hmeq_bad_nona <- hmeq %>%  filter(BAD ==1 ) %>%  drop_na()

unique_over_bad <- sampled_hmeq %>% filter(BAD == 1)

unique_over_bad <- unique_over_bad %>%  group_by(ID) %>%  slice(1) %>% ungroup()

hmeq_good_nona <- hmeq %>%  filter(BAD ==0 ) %>%  drop_na()

unique_over_good <- sampled_hmeq %>% filter(BAD == 0)

unique_over_good <- unique_over_good %>%  group_by(ID) %>%  slice(1) %>% ungroup()





sampled_hmeq %>%  ggplot(aes(x = ID , fill = as.factor(BAD) )) + geom_histogram(binwidth =  1) + facet_grid(~BAD) + labs(title = "HMEQ BOTH OVER and UNDER"  , caption = "You can see that the underweight class is used a high number of times")


```





#omit nas


### the lgd set has no missing values, so oversampling works as expected

```{r ,fig.width = 5,fig.asp = 0.618, fig.align='center'}

#ll  <- na.omit(lgd)
#hmeq <- na.omit(hmeq)



#############################################################################
library(ROSE)

#hmeq <- na.omit(hmeq)
table(lgd$event)

#hmeq <- hmeq %>% mutate(fill_notnull = 1)

lgd$ID <- seq.int(nrow(lgd))

# for over and under, missing values skew

# Calculate the required number of cases in the over-sampled dataset
 n_new <- 1817/(1-0.5)  # 

# Over-sample
oversampling_result <- ovun.sample(formula = event ~ ., data = lgd,
                           method = "over", N = n_new, seed = 2019)

# Verify the Class-balance of the over-sampled dataset
oversampled_lgd <- oversampling_result$data
prop.table(table(oversampled_lgd$event))



oversampled_lgd %>%  ggplot(aes(x = ID , fill = as.factor(event) )) + geom_histogram(binwidth =  1) + facet_grid(~event) + labs(title = "LGD oversample")
```

```{r  ,fig.width = 5,fig.asp = 0.618, fig.align='center' }



##############################################################################
table(lgd$event)

 n_new <- 728/(0.5)  # 4771 is the number of bads (non-goods)

# Over-sample
undersampling_result <- ovun.sample(formula = event ~ ., data = lgd,
                           method = "under", N = n_new, seed = 2019)

# Verify the Class-balance of the over-sampled dataset
undersampled_lgd <- undersampling_result$data
prop.table(table(undersampled_lgd$event))



undersampled_lgd %>%  ggplot(aes(x = ID , fill = as.factor(event) )) + geom_histogram(binwidth =  1) + facet_grid(~event) + labs(title = "LGD undersample")



```





